Mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #on pointe vers noyau
    path('', include('noyau.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls'))
]

noyau/urls.py
# Supprimer la ligne : from django.contrib import admin
from django.urls import path

# importer les Views dans laquelle on enverra les requests
from . import views

# Plutard, Quand on voudra créer des urls pour les clients, dynamiquement
app_name = "noyau"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("subscribe/", views.subscribe, name="subscribe"),
    path("logout/", views.logout_request, name="logout"),
    path("connexion/", views.demandeConnexion, name="connexion"),
    path("account/", views.account, name="account"),
    path("searchbar/", views.searchbar, name="searchbar"),

]

noyau/models.py
from django.db import models
from django.db.models.fields import DateTimeField
from datetime import datetime

# Create your models here.
class Netfeelex(models.Model):
    #CharFiels pour mettre une restriction
    Titre_film = models.CharField(max_length=200)
    Contenu_film = models.TextField()
    Date_publication = models.DateTimeField("Date publié", default = datetime.now())

    #fonction de recuperation
    def __str__(self):
        return self.Titre_film

noyau/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class newUser(UserCreationForm):
    courriel = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "courriel",
            "password1",
            "password2"
        )

def save(self, commit=True):
    utilisateur = super(newUser, self).save(commit=False)
    utilisateur.first_name = self.cleaned_data["first_name"]
    utilisateur.last_name = self.cleaned_data["last_name"]
    utilisateur.email = self.cleaned_data["courriel"]
    if commit:
        utilisateur.save()
        return utilisateur

noyau/views.py
from random import randint
from django.db.models.expressions import Random
from django.shortcuts import render, redirect
from .models import Netfeelex
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import newUser

# Create your views here.

def homepage(request):
    return render(request=request, template_name='main/home.html',
                  context={"netfeelex": Netfeelex.objects.all})

def searchbar(request):
    if request.method == "POST":
      searched = request.POST['searched']
      mod = Netfeelex.objects.filter(Titre_film=searched)
      return render(request,'main/searchbar.html',{
          'searched' :searched,
          'mod' : mod,
      })

def subscribe(request): 
    if request.method == "POST":
        form = newUser(request.POST)

        if form.is_valid():
            # on créer utilisateur
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"nouveau compte créé: {username}")
            login(request, user)
            messages.info(request, f"vous êtes maintenant connecté en tant que {username}")
            return redirect("noyau:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}:{form.error_messages[msg]}")
                return render(request, "main/subscribe.html", {"formulaire": form})

    form = newUser
    return render(request, "main/subscribe.html", {"formulaire": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Session est fermée")
    return redirect("noyau:homepage")


def demandeConnexion(request):
    if request.method == "POST":
        form = AuthenticationForm(request = request, data = request.POST)

        if form.is_valid():
            nomUtilisateur = form.cleaned_data.get('username')
            motDePasse = form.cleaned_data.get('password')
            user = authenticate(username = nomUtilisateur, password = motDePasse)

            if user is not None:
                login(request,user)
                messages.info(request, f"Vous êtes maintenant connecté étant que {nomUtilisateur}")
                return redirect("/")
            else:
                messages.error(request, "Nom d'Utilisateur ou Mot de Passe non valide !")
        else:
            messages.error(request, "Nom d'Utilisateur ou Mot de Passe non valide !")

    form = AuthenticationForm()
    return render(request, "main/connexion.html", {"formulaire": form})


def account(request):
    i = randint(0,10)
    motGentil(request,i)
    return redirect("/")


def motGentil(request, argument):
    if argument == 1:
        messages.info(request, "Souriez ♥")
    elif argument == 2:
        messages.info(request, "Je sais, C'est un très beau Prenom")
    elif argument == 3:
        messages.info(request, "Arrête d'avoir envie, Fais-le")
    elif argument == 4:
        messages.info(request, "Mieux vaut ne pas le savoir")
    elif argument == 5:
        messages.info(request, "Tu connais la chanson ♫ Taciturne ♪ de Dinos ?")
    elif argument == 6:
        messages.info(request, "Oui, c'est mon nom, tu doutes ?")
    elif argument == 7:
        messages.info(request, "C'est bientôt Noël ?")
    elif argument == 8:
        messages.info(request, "Le monde est trop petit pour...")
    elif argument == 9:
        messages.info(request, "Tu me ressembles ☺")
    elif argument == 10:
        messages.info(request, "Je te vois ☻")
    else:
        messages.info(request, "Salut, tu vas bien ?")

noyau/templates/main/connexion.html
{% extends "main/header.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{formulaire.as_p}}
    <button style="background-color: rgb(9, 128, 25); color: white;" type="submit" class="btn btn-outline-info">connexion</button>
</form>
Si vous n'avez pas un compte, <a href="/subscribe"><strong>enregistrez-vous</strong></a>
{% endblock %}

noyau/templates/main/header.html
<head>
    {% load static %}
    <!-- Prism CSS -->
    <link href="{% static "tinymce/css/prism.css" %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/lux/bootstrap.min.css" integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
</head>

<body>

    {% include "main/includes/navbar.html" %}
    {% include "main/includes/messages.html" %}
    <div class = "container">
        <br>
        {% block content %}

        {% endblock %}
    </div>

</body>

<!-- Prism JS -->
<script src="{% static "tinymce/js/prism.js" %}"></script>

noyau/templates/main/home.html
{% extends "main/header.html" %}

{% block content %}
    <div class="row">
        {% for n in netfeelex %}
        <div class="col s12 m6 l4">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">{{n.Titre_film}}</span>
                    <p>{{n.Contenu_film | safe }}</p>
                    <p style="font-size:70%">{{n.Date_publication |safe}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

noyau/templates/main/includes/messages.html
{% if messages %}
{% for message in messages %}
    {% if message.tags == 'success'%}
    <script>M.toast({ html: "{{message}}", classes: 'green rounded', displayLength: 2000 });</script>
    {% elif message.tags == 'info'%}
    <script>M.toast({ html: "{{message}}", classes: 'blue rounded', displayLength: 2000 });</script>
    {% elif message.tags == 'warning'%}
    <script>M.toast({ html: "{{message}}", classes: 'orange rounded', displayLength: 10000 });</script>
    {% elif message.tags == 'error'%}
    <script>M.toast({ html: "{{message}}", classes: 'red rounded', displayLength: 10000 });</script>
    {% endif %}
{% endfor %}
{% endif %}

noyau/templates/main/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Film</a>
     
  
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="/">Page Principal
              
            </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/account">{{user.username}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout">logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/subscribe">Enregistrer</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/connexion">Connexion</a>
          </li>
          {% endif %}
          
        </ul>
        <form class="d-flex" method= POST action="{% url 'noyau:searchbar' %}">
            {% csrf_token %} 
               <input class="form-control me-2"
               type="search" placeholder="Search" aria-label="Search" name="searched">
          <button class="btn  btn-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

noyau/templates/main/searchbar.html
{% extends "main/header.html" %}

{% block content %}
   
         {% if searched %}
            <h1>You searched For</h1>
            <br/>
            {% for netfeelex in mod %}
                {{netfeelex}}<br/>
                <iframe>{{netfeelex.Contenu_film}}</iframe><br/>
                {{netfeelex.Date_publication}}<br/>    

            {% endfor %}
        

        {% endif %}

{% endblock %}

noyau/templates/main/subscribe.html
{% extends "main/header.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{formulaire.as_p}}
    <button class="btn" style="background-color: rgb(115, 117, 0); color: rgb(255, 255, 255); font-weight: bold;" type="submit">Enregistrer</button>
</form>
Si vous avez déjà un compte, <a href="/connexion"><strong>login</strong></a>

{% endblock %}